### ISSUE TITLE
Get metadata in JSON

### ISSUE THREAD

**Issue by NightMachinary** [FicHub/fichub-cli#9]
Ala `fanficfare --meta-only --json-meta "$url" `. It’d be good if the keys (JSON structure) are compatible with fanficfare, too.

**Comment by arzkar** [comment]
Unfortunately, the fichub-cli wont be able to provide a fanficfare compatible metadata since the CLI was simply made to download from the Fichub API and  the API is not currently exposing all the metadata which will be needed to make a json compatible with fanficfare's and it might not be added for a long time.

If I may ask, why not use fanficfare for metadata scraping? Its quite fast for that purpose.

**Comment by NightMachinary** [comment]
@arzkar I’m fine with a best-efforts basis, no need for full compatibility. 

fanficfare has problems with ff.net’s Cloudflare policies.

**Comment by arzkar** [comment]
Currently very little metadata is provided by the fichub API and I will need to clean the meta to make it consumable.
If you only want FanfictionNet's metadata, you can use one of my other projects called [Fanfiction Finder API](https://github.com/arzkar/Fanfiction-Finder-API) which can get metadata from both FFNet and AO3. It uses cloudscraper like fanficfare does but it seems to be able to get the metadata without any issue. There's a delay of 2s between each request which prevents it from getting rate-limited. Let me know if you find any bugs with that.

**Comment by arzkar** [comment]
I have added a new `--meta-json` flag which can be used to get all the metadata that Fichub API currently provides. It will in v3.6 which will be released in a few minutes.
